version: 2
jobs:
  test-future:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/tiny-go/fn/future
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd future
            go mod vendor
      - run:
          name: Unit tests
          command: |
            cd future
            go test -v -race ./...
  test-retry:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/tiny-go/fn/retry
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd retry
            go mod vendor
      - run:
          name: Unit tests
          command: |
            cd retry
            go test -v -race ./...
  test-sync:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/tiny-go/fn/retry
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd sync
            go mod vendor
      - run:
          name: Unit tests
          command: |
            cd sync
            go test -v -race ./...
workflows:
  version: 2
  test_all:
    jobs:
      - test-future
      - test-retry
      - test-sync
